export const performancePlatformDDL = [
  `CREATE INDEX IF NOT EXISTS staff_slots_current ON staff_line_minute_slots(tenant_id,slot)`,
  `CREATE TABLE IF NOT EXISTS assistant_oa_work (tenant_id TEXT NOT NULL,oa_id TEXT NOT NULL,lease_id TEXT,lease_until TEXT,next_at TEXT NOT NULL DEFAULT '',last_run_at TEXT NOT NULL DEFAULT '',failures INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(tenant_id,oa_id))`,
  `CREATE INDEX IF NOT EXISTS assistant_oa_work_due ON assistant_oa_work(next_at,last_run_at)`,
  `CREATE TABLE IF NOT EXISTS staff_line_delivery_schedule (notice_id TEXT PRIMARY KEY,next_at TEXT NOT NULL DEFAULT '')`,
  `CREATE INDEX IF NOT EXISTS staff_notices_queue ON staff_line_notices(tenant_id,oa_id,state,created_at,user_id)`,
  `CREATE INDEX IF NOT EXISTS staff_delivery_attempt ON staff_line_deliveries(last_attempt_at)`,
  `CREATE INDEX IF NOT EXISTS accounts_ready ON accounts(state,id)`,
];
export const performanceCommonDDL = [
  `CREATE TABLE IF NOT EXISTS assistant_customer_changes (oa_id TEXT NOT NULL,customer_id TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(oa_id,customer_id))`,
  `CREATE INDEX IF NOT EXISTS customer_links_customer ON customer_links(customer_id,oa_id,state)`,
  `CREATE INDEX IF NOT EXISTS customer_links_oa_customer ON customer_links(oa_id,customer_id,state)`,
  `CREATE TRIGGER IF NOT EXISTS assistant_customer_updated AFTER UPDATE OF name,owner_user_id,team_id,mode,stage,opt_out,version ON customers BEGIN INSERT INTO assistant_customer_changes(oa_id,customer_id) SELECT oa_id,customer_id FROM customer_links WHERE customer_id=NEW.id ON CONFLICT(oa_id,customer_id) DO UPDATE SET revision=revision+1; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_link_insert AFTER INSERT ON customer_links BEGIN INSERT INTO assistant_customer_changes(oa_id,customer_id) VALUES (NEW.oa_id,NEW.customer_id) ON CONFLICT(oa_id,customer_id) DO UPDATE SET revision=revision+1; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_link_update AFTER UPDATE ON customer_links BEGIN INSERT INTO assistant_customer_changes(oa_id,customer_id) VALUES (OLD.oa_id,OLD.customer_id) ON CONFLICT(oa_id,customer_id) DO UPDATE SET revision=revision+1; INSERT INTO assistant_customer_changes(oa_id,customer_id) VALUES (NEW.oa_id,NEW.customer_id) ON CONFLICT(oa_id,customer_id) DO UPDATE SET revision=revision+1; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_link_delete AFTER DELETE ON customer_links BEGIN INSERT INTO assistant_customer_changes(oa_id,customer_id) VALUES (OLD.oa_id,OLD.customer_id) ON CONFLICT(oa_id,customer_id) DO UPDATE SET revision=revision+1; END`,
];
export const performanceHarnessDDL = [
  `CREATE TABLE IF NOT EXISTS outbox_reconcile_queue (outbox_id TEXT PRIMARY KEY,revision INTEGER NOT NULL DEFAULT 1)`,
  `CREATE TABLE IF NOT EXISTS delivery_maintenance (id TEXT PRIMARY KEY)`,
  `INSERT OR IGNORE INTO outbox_reconcile_queue(outbox_id) SELECT id FROM outbox WHERE state IN ('sent','uncertain') AND NOT EXISTS(SELECT 1 FROM delivery_maintenance WHERE id='reconcile-seed')`,
  `INSERT OR IGNORE INTO delivery_maintenance(id) VALUES ('reconcile-seed')`,
  `CREATE TRIGGER IF NOT EXISTS delivery_reconcile_insert AFTER INSERT ON outbox WHEN NEW.state IN ('sent','uncertain') BEGIN INSERT INTO outbox_reconcile_queue(outbox_id) VALUES (NEW.id) ON CONFLICT(outbox_id) DO UPDATE SET revision=revision+1; END`,
  `CREATE TRIGGER IF NOT EXISTS delivery_reconcile_update AFTER UPDATE OF state ON outbox WHEN NEW.state IN ('sent','uncertain') AND OLD.state<>NEW.state BEGIN INSERT INTO outbox_reconcile_queue(outbox_id) VALUES (NEW.id) ON CONFLICT(outbox_id) DO UPDATE SET revision=revision+1; END`,
  `CREATE TABLE IF NOT EXISTS assistant_message_changes (customer_id TEXT PRIMARY KEY,revision INTEGER NOT NULL DEFAULT 1)`,
  `CREATE INDEX IF NOT EXISTS messages_customer_occurred ON messages(customer_id,occurred_at DESC,id DESC)`,
  `CREATE INDEX IF NOT EXISTS events_pending ON events(state,occurred_at)`,
  `CREATE INDEX IF NOT EXISTS outbox_proposal ON outbox(proposal_id,proposal_version)`,
  `CREATE TRIGGER IF NOT EXISTS assistant_message_insert AFTER INSERT ON messages BEGIN INSERT INTO assistant_message_changes(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_message_update AFTER UPDATE ON messages BEGIN INSERT INTO assistant_message_changes(customer_id) VALUES (OLD.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1; INSERT INTO assistant_message_changes(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_message_delete AFTER DELETE ON messages BEGIN INSERT INTO assistant_message_changes(customer_id) VALUES (OLD.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1; END`,
];
export const performanceTsunaguDDL = [
  `CREATE TABLE IF NOT EXISTS assistant_expiry_queue (proposal_id TEXT PRIMARY KEY,due_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS assistant_expiry_due ON assistant_expiry_queue(due_at,proposal_id)`,
  `CREATE TABLE IF NOT EXISTS assistant_maintenance (id TEXT PRIMARY KEY)`,
  `INSERT OR IGNORE INTO assistant_expiry_queue(proposal_id,due_at) SELECT a.proposal_id,a.expires_at FROM assistant_proposals a JOIN proposals p ON p.id=a.proposal_id WHERE p.state IN ('pending','approved','held') AND NOT EXISTS(SELECT 1 FROM assistant_maintenance WHERE id='expiry-seed')`,
  `INSERT OR IGNORE INTO assistant_maintenance(id) VALUES ('expiry-seed')`,
  `CREATE TRIGGER IF NOT EXISTS assistant_expiry_insert AFTER INSERT ON assistant_proposals BEGIN INSERT INTO assistant_expiry_queue(proposal_id,due_at) VALUES (NEW.proposal_id,NEW.expires_at) ON CONFLICT(proposal_id) DO UPDATE SET due_at=excluded.due_at; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_expiry_change AFTER UPDATE OF expires_at ON assistant_proposals BEGIN INSERT INTO assistant_expiry_queue(proposal_id,due_at) VALUES (NEW.proposal_id,NEW.expires_at) ON CONFLICT(proposal_id) DO UPDATE SET due_at=excluded.due_at; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_expiry_finish AFTER UPDATE OF state ON proposals WHEN NEW.state IN ('sent','cancelled','expired','uncertain') BEGIN DELETE FROM assistant_expiry_queue WHERE proposal_id=NEW.id; END`,
  `CREATE TABLE IF NOT EXISTS assistant_ingest_cursors (id TEXT PRIMARY KEY,cursor TEXT NOT NULL DEFAULT '')`,
  `CREATE TABLE IF NOT EXISTS assistant_source_backoff (kind TEXT PRIMARY KEY,failures INTEGER NOT NULL DEFAULT 0,next_at TEXT NOT NULL DEFAULT '')`,
  `CREATE TABLE IF NOT EXISTS assistant_work_queue (sequence INTEGER PRIMARY KEY AUTOINCREMENT,customer_id TEXT NOT NULL UNIQUE,revision INTEGER NOT NULL DEFAULT 1,priority INTEGER NOT NULL DEFAULT 1,due_at TEXT NOT NULL DEFAULT '',lease_id TEXT,lease_until TEXT,attempts INTEGER NOT NULL DEFAULT 0)`,
  `CREATE INDEX IF NOT EXISTS assistant_work_due ON assistant_work_queue(priority,due_at,sequence)`,
  `CREATE TABLE IF NOT EXISTS assistant_sweep (id TEXT PRIMARY KEY,revision INTEGER NOT NULL DEFAULT 1,active_revision INTEGER NOT NULL DEFAULT 0,completed_revision INTEGER NOT NULL DEFAULT 0,cursor TEXT NOT NULL DEFAULT '',next_at TEXT NOT NULL DEFAULT '')`,
  `INSERT OR IGNORE INTO assistant_sweep(id) VALUES ('default')`,
  `CREATE INDEX IF NOT EXISTS proposals_customer_state ON proposals(customer_id,state,created_at)`,
  `CREATE INDEX IF NOT EXISTS proposals_state_created ON proposals(state,created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS proposals_created ON proposals(created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS context_customer_created ON context_notes(customer_id,created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS context_confirmed_created ON context_notes(created_at DESC) WHERE confirmed_by IS NOT NULL AND deleted_at IS NULL`,
  `CREATE INDEX IF NOT EXISTS assistant_sources_published ON assistant_sources(published_at DESC)`,
  `CREATE INDEX IF NOT EXISTS assistant_sources_updated ON assistant_sources(updated_at DESC)`,
  `CREATE INDEX IF NOT EXISTS assistant_proposals_owner_expiry ON assistant_proposals(owner_user_id,expires_at)`,
  `CREATE INDEX IF NOT EXISTS assistant_proposals_expiry ON assistant_proposals(expires_at)`,
  `CREATE TRIGGER IF NOT EXISTS assistant_dirty_context_notes_insert AFTER INSERT ON context_notes BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_dirty_context_notes_update AFTER UPDATE ON context_notes BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (OLD.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; INSERT INTO assistant_work_queue(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_dirty_context_notes_delete AFTER DELETE ON context_notes BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (OLD.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_dirty_assistant_preferences_insert AFTER INSERT ON assistant_preferences BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_dirty_assistant_preferences_update AFTER UPDATE ON assistant_preferences BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (OLD.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; INSERT INTO assistant_work_queue(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_dirty_assistant_preferences_delete AFTER DELETE ON assistant_preferences BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (OLD.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_decision_work AFTER UPDATE OF state ON proposals WHEN NEW.state IN ('sent','cancelled') AND OLD.state<>NEW.state BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_source_insert AFTER INSERT ON assistant_sources BEGIN UPDATE assistant_sweep SET revision=revision+1 WHERE id='default'; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_source_update AFTER UPDATE ON assistant_sources BEGIN UPDATE assistant_sweep SET revision=revision+1 WHERE id='default'; END`,
  `CREATE TRIGGER IF NOT EXISTS assistant_source_delete AFTER DELETE ON assistant_sources BEGIN UPDATE assistant_sweep SET revision=revision+1 WHERE id='default'; END`,
];
