/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.showcase.jsonc --include-runtime=false --env-interface=ShowcaseBindings backend/showcase-bindings.d.ts` (hash: 79ae1858c4f9443f2e13447eaaa336ce)
interface __BaseEnv_ShowcaseBindings {
	PLATFORM_DB: D1Database;
	ASSETS: Fetcher;
	APP_ORIGIN: "https://tsunagu-gs-showcase.shimoryo.workers.dev";
	SHOWCASE_DATABASES: DurableObjectNamespace<import("./showcase-worker").ShowcaseDatabase>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./showcase-worker");
		durableNamespaces: "ShowcaseDatabase";
	}
	interface Env extends __BaseEnv_ShowcaseBindings {}
}
interface ShowcaseBindings extends __BaseEnv_ShowcaseBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN">> {}
}
