/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.showcase.jsonc --include-runtime=false --env-interface=ShowcaseBindings backend/showcase-bindings.d.ts` (hash: e09bd47d89215840409f822ecd7f6f81)
interface __BaseEnv_ShowcaseBindings {
	PLATFORM_DB: D1Database;
	SHOWCASE_COMMON_DB: D1Database;
	SHOWCASE_HARNESS_DB: D1Database;
	SHOWCASE_STUDIO_DB: D1Database;
	ASSETS: Fetcher;
	APP_ORIGIN: "https://tsunagu-gs-showcase.shimoryo.workers.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./showcase-worker");
	}
	interface Env extends __BaseEnv_ShowcaseBindings {}
}
interface ShowcaseBindings extends __BaseEnv_ShowcaseBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN">> {}
}
