CREATE TABLE IF NOT EXISTS assistant_expiry_queue (proposal_id TEXT PRIMARY KEY,due_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS assistant_expiry_due ON assistant_expiry_queue(due_at,proposal_id);
CREATE TABLE IF NOT EXISTS assistant_maintenance (id TEXT PRIMARY KEY);
INSERT OR IGNORE INTO assistant_expiry_queue(proposal_id,due_at) SELECT a.proposal_id,a.expires_at FROM assistant_proposals a JOIN proposals p ON p.id=a.proposal_id WHERE p.state IN ('pending','approved','held') AND NOT EXISTS(SELECT 1 FROM assistant_maintenance WHERE id='expiry-seed');
INSERT OR IGNORE INTO assistant_maintenance(id) VALUES ('expiry-seed');
CREATE TRIGGER IF NOT EXISTS assistant_expiry_insert AFTER INSERT ON assistant_proposals BEGIN INSERT INTO assistant_expiry_queue(proposal_id,due_at) VALUES (NEW.proposal_id,NEW.expires_at) ON CONFLICT(proposal_id) DO UPDATE SET due_at=excluded.due_at; END;
CREATE TRIGGER IF NOT EXISTS assistant_expiry_change AFTER UPDATE OF expires_at ON assistant_proposals BEGIN INSERT INTO assistant_expiry_queue(proposal_id,due_at) VALUES (NEW.proposal_id,NEW.expires_at) ON CONFLICT(proposal_id) DO UPDATE SET due_at=excluded.due_at; END;
CREATE TRIGGER IF NOT EXISTS assistant_expiry_finish AFTER UPDATE OF state ON proposals WHEN NEW.state IN ('sent','cancelled','expired','uncertain') BEGIN DELETE FROM assistant_expiry_queue WHERE proposal_id=NEW.id; END;
CREATE TABLE IF NOT EXISTS assistant_ingest_cursors (id TEXT PRIMARY KEY,cursor TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS assistant_source_backoff (kind TEXT PRIMARY KEY,failures INTEGER NOT NULL DEFAULT 0,next_at TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS assistant_work_queue (sequence INTEGER PRIMARY KEY AUTOINCREMENT,customer_id TEXT NOT NULL UNIQUE,revision INTEGER NOT NULL DEFAULT 1,priority INTEGER NOT NULL DEFAULT 1,due_at TEXT NOT NULL DEFAULT '',lease_id TEXT,lease_until TEXT,attempts INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS assistant_work_due ON assistant_work_queue(priority,due_at,sequence);
CREATE TABLE IF NOT EXISTS assistant_sweep (id TEXT PRIMARY KEY,revision INTEGER NOT NULL DEFAULT 1,active_revision INTEGER NOT NULL DEFAULT 0,completed_revision INTEGER NOT NULL DEFAULT 0,cursor TEXT NOT NULL DEFAULT '',next_at TEXT NOT NULL DEFAULT '');
INSERT OR IGNORE INTO assistant_sweep(id) VALUES ('default');
CREATE INDEX IF NOT EXISTS proposals_customer_state ON proposals(customer_id,state,created_at);
CREATE INDEX IF NOT EXISTS proposals_state_created ON proposals(state,created_at DESC);
CREATE INDEX IF NOT EXISTS proposals_created ON proposals(created_at DESC);
CREATE INDEX IF NOT EXISTS context_customer_created ON context_notes(customer_id,created_at DESC);
CREATE INDEX IF NOT EXISTS context_confirmed_created ON context_notes(created_at DESC) WHERE confirmed_by IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS assistant_sources_published ON assistant_sources(published_at DESC);
CREATE INDEX IF NOT EXISTS assistant_sources_updated ON assistant_sources(updated_at DESC);
CREATE INDEX IF NOT EXISTS assistant_proposals_owner_expiry ON assistant_proposals(owner_user_id,expires_at);
CREATE INDEX IF NOT EXISTS assistant_proposals_expiry ON assistant_proposals(expires_at);
CREATE TRIGGER IF NOT EXISTS assistant_dirty_context_notes_insert AFTER INSERT ON context_notes BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END;
CREATE TRIGGER IF NOT EXISTS assistant_dirty_context_notes_update AFTER UPDATE ON context_notes BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (OLD.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; INSERT INTO assistant_work_queue(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END;
CREATE TRIGGER IF NOT EXISTS assistant_dirty_context_notes_delete AFTER DELETE ON context_notes BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (OLD.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END;
CREATE TRIGGER IF NOT EXISTS assistant_dirty_assistant_preferences_insert AFTER INSERT ON assistant_preferences BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END;
CREATE TRIGGER IF NOT EXISTS assistant_dirty_assistant_preferences_update AFTER UPDATE ON assistant_preferences BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (OLD.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; INSERT INTO assistant_work_queue(customer_id) VALUES (NEW.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END;
CREATE TRIGGER IF NOT EXISTS assistant_dirty_assistant_preferences_delete AFTER DELETE ON assistant_preferences BEGIN INSERT INTO assistant_work_queue(customer_id) VALUES (OLD.customer_id) ON CONFLICT(customer_id) DO UPDATE SET revision=revision+1,due_at='',priority=MIN(priority,1),attempts=0; END;
CREATE TRIGGER IF NOT EXISTS assistant_source_insert AFTER INSERT ON assistant_sources BEGIN UPDATE assistant_sweep SET revision=revision+1 WHERE id='default'; END;
CREATE TRIGGER IF NOT EXISTS assistant_source_update AFTER UPDATE ON assistant_sources BEGIN UPDATE assistant_sweep SET revision=revision+1 WHERE id='default'; END;
CREATE TRIGGER IF NOT EXISTS assistant_source_delete AFTER DELETE ON assistant_sources BEGIN UPDATE assistant_sweep SET revision=revision+1 WHERE id='default'; END;
