// Every person, event and metric below is demonstration data.
export const demoDate = "2026-09-21";
export const customers = [
  {
    id: "tanaka",
    name: "田中 翔太",
    initial: "田",
    color: "blue",
    subtitle: "品川区・都心マンション",
    stage: "検討中",
    mode: "ai",
    budget: "5,500万円",
    area: "港区・品川区",
    wish: "駅から徒歩7分以内 / 2LDK",
    concern: "金利が上がったときの、月々の返済額が気になっている。",
    promise: "9月25日までに資金計画の比較表を共有",
    last: "金利解説の動画を視聴",
    seen: "10分前",
  },
  {
    id: "yamamoto",
    name: "山本 美咲",
    initial: "山",
    color: "peach",
    subtitle: "都心・中古リノベーション",
    stage: "商談後",
    mode: "ai",
    budget: "4,800万円",
    area: "目黒区・渋谷区",
    wish: "駅徒歩5分以内 / 1LDK",
    concern: "頭金を支払ったあとの、手元資金が不安。初期費用を抑えたい。",
    promise: "初期費用の分割プランを案内",
    last: "初回商談から4日経過",
    seen: "40分前",
  },
  {
    id: "watanabe",
    name: "渡辺 大輔",
    initial: "渡",
    color: "sage",
    subtitle: "店舗開業に向けた物件探し",
    stage: "再連絡",
    mode: "ai",
    budget: "3,200万円",
    area: "世田谷区",
    wish: "路面店舗 / 15坪以上",
    concern: "融資の審査結果を待っている。結果に合わせて物件の契約を進めたい。",
    promise: "9月下旬に融資審査の進捗を確認",
    last: "お約束の連絡日になりました",
    seen: "本日",
  },
  {
    id: "takahashi",
    name: "高橋 優子",
    initial: "高",
    color: "rose",
    subtitle: "文京区・ファミリー向け3LDK",
    stage: "保留中",
    mode: "ai",
    budget: "7,000万円",
    area: "文京区",
    wish: "希望学区内 / 3LDK",
    concern: "転勤の可能性が出てきたため、購入条件を確認し直す必要がある。",
    promise: "異動の見込みが分かり次第、希望条件を再確認",
    last: "新着返信を受信",
    seen: "5分前",
  },
  {
    id: "nakamura",
    name: "中村 慎吾",
    initial: "中",
    color: "lavender",
    subtitle: "賃貸更新に合わせた住み替え",
    stage: "面談済み",
    mode: "ai",
    budget: "6,000万円",
    area: "品川区",
    wish: "2LDK / 60㎡以上",
    concern: "現在の賃貸借契約の更新月まで待つべきか迷っている。",
    promise: "9月28日までに中途解約の条件を確認",
    last: "本日14:00の面談が終了",
    seen: "15:00",
  },
  {
    id: "kobayashi",
    name: "小林 誠",
    initial: "小",
    color: "stone",
    subtitle: "成約・契約締結の準備",
    stage: "成約済み",
    mode: "stopped",
    budget: "6,200万円",
    area: "目黒区",
    wish: "新築マンション / 2LDK",
    concern: "重要事項説明の日程調整を希望。",
    promise: "来週水曜日に店舗で契約締結",
    last: "契約に向けて合意",
    seen: "昨日",
  },
];
export const assets = [
  {
    id: "rate",
    title: "金利タイプ別・返済額の比較表",
    description: "固定と変動の違いを、月々の返済額から整理。",
    kind: "PDF",
    source: "営業資料",
    color: "blue",
    tag: "資金計画",
    approval: 92,
    appointment: 18,
    status: "公開中",
  },
  {
    id: "cost",
    title: "頭金を抑えた、住まいの買い方",
    description: "初期費用の内訳と支払い方法を解説する事例集。",
    kind: "ARTICLE",
    source: "LINE Harness",
    color: "peach",
    tag: "購入事例",
    approval: 88,
    appointment: 14,
    status: "公開中",
  },
  {
    id: "loan",
    title: "開業準備と融資のチェックリスト",
    description: "審査後に必要になる書類と次のステップ。",
    kind: "GUIDE",
    source: "営業資料",
    color: "sage",
    tag: "店舗・事業用",
    approval: 90,
    appointment: 16,
    status: "公開中",
  },
  {
    id: "property",
    title: "本駒込 3LDK リノベーション",
    description: "希望学区内の新着物件。間取りと周辺環境を整理。",
    kind: "PROPERTY",
    source: "Google Sheets",
    color: "lavender",
    tag: "新着物件",
    approval: 85,
    appointment: 12,
    status: "公開中",
  },
  {
    id: "archive",
    title: "夏の住み替えキャンペーン",
    description: "キャンペーン終了につき、新規提案への使用を停止。",
    kind: "PDF",
    source: "営業資料",
    color: "stone",
    tag: "キャンペーン",
    approval: 81,
    appointment: 10,
    status: "失効",
  },
];
export const initialCandidates = [
  {
    id: "p1",
    customerId: "tanaka",
    category: "閲覧後",
    status: "pending",
    assetId: "rate",
    time: "18:30",
    trigger: "金利の解説動画を視聴",
    reason:
      "前回の面談で伺った「月々の返済額への不安」と、今回閲覧した動画の内容が一致しています。比較表を添えて、検討をお手伝いする提案です。",
    evidence: ["9/21 09:10 動画の閲覧履歴", "9/15 商談メモ：金利上昇への不安"],
    draft:
      "田中様、こんにちは。ネクスト・プロパティの佐藤です。\n\n資金計画の動画をご覧いただき、ありがとうございます。前回お話しされていた、金利が上がった場合の月々の返済額について、比較表をご用意しました。\n\n今週木曜か金曜に、15分ほどお電話でご説明することも可能です。ご都合はいかがでしょうか？",
  },
  {
    id: "p2",
    customerId: "yamamoto",
    category: "商談後",
    status: "pending",
    assetId: "cost",
    time: "19:15",
    trigger: "初回商談から4日が経過",
    reason:
      "面談で伺った手元資金への不安に対し、初期費用を抑えた購入事例をご案内します。物件の紹介を急がず、懸念を解消する内容です。",
    evidence: ["9/17 初回商談メモ", "希望条件：頭金と初期費用を抑えたい"],
    draft:
      "山本様、こんにちは。先日はお時間をいただき、ありがとうございました。\n\nお話しされていた頭金と初期費用について、支払い方を工夫した事例をまとめました。お手元に残す資金を確認しながら、無理のない計画を一緒に考えられればと思います。\n\n気になる点があれば、いつでもお気軽にご連絡ください。",
  },
  {
    id: "p3",
    customerId: "watanabe",
    category: "お約束",
    status: "pending",
    assetId: "loan",
    time: "17:00",
    trigger: "お約束していた連絡日",
    reason:
      "前回の電話で「9月下旬に審査結果が出る頃に連絡」とお約束しています。進捗を伺う、短いご連絡を提案します。",
    evidence: ["9/7 電話メモ", "次回連絡：約束日 9/21"],
    draft:
      "渡辺様、こんにちは。ネクスト・プロパティの佐藤です。\n\n以前伺っていた融資審査の時期になりましたので、ご連絡しました。その後の進捗はいかがでしょうか？\n\n追加の書類や物件探しでお手伝いできることがあれば、いつでもお知らせください。",
  },
  {
    id: "p4",
    customerId: "takahashi",
    category: "新着物件",
    status: "held",
    assetId: "property",
    time: "18:00",
    trigger: "送信前に、新しい返信を受信",
    hold: "「急遽、来月に異動が決まりそうです」と返信がありました。購入エリアや時期が変わる可能性があるため、物件のご案内を保留しています。",
    reason:
      "希望学区内で条件に合う物件が登録されましたが、最新の返信を優先して状況の確認が必要です。",
    evidence: ["9/21 09:15 LINEの新着返信", "9/21 09:00 物件マスタ更新"],
    draft:
      "高橋様、こんにちは。ご希望の学区内で、新しい3LDK物件が登録されました。\n\n駅までの距離とご予算も伺った条件に近いため、概要をお送りします。ご興味がございましたら、内見の日程をご相談させてください。",
  },
];
export const initialMeetings = [
  {
    id: "m1",
    customerId: "nakamura",
    time: "14:00",
    duration: "60分",
    format: "Google Meet",
    confirmed: false,
    attendance: "実施済み",
    outcome: "継続検討",
    next: "9/28までに中途解約違約金の有無を確認。10月上旬に再面談。",
    note: "物件は好感触。現在の賃貸更新月まで待つかを検討中。",
    mode: "ai",
  },
  {
    id: "m2",
    customerId: "kobayashi",
    time: "16:30",
    duration: "45分",
    format: "対面",
    confirmed: false,
    attendance: "実施済み",
    outcome: "成約",
    next: "来週水曜日に店舗で契約締結。",
    note: "重要事項説明の日程を調整する。",
    mode: "stopped",
  },
];
export const initialLinks = [
  {
    id: "l1",
    customerId: "tanaka",
    title: "資金計画のオンライン相談",
    source: "TimeRex",
    date: "9/21 14:00",
    basis: "氏名・メールアドレスが一致",
    summary: "金利上昇時の返済額と、都内マンション購入の予算について相談。",
    linked: false,
  },
  {
    id: "l2",
    customerId: "takahashi",
    title: "品川カフェでの住まい相談",
    source: "ボイスメモ",
    date: "9/21 11:30",
    basis: "希望エリア・予算・家族構成が一致",
    summary: "文京区の3LDK、予算7,000万円未満。購入時期の再確認が必要。",
    linked: false,
  },
  {
    id: "l3",
    customerId: "yamamoto",
    title: "購入費用の個別面談",
    source: "Google Meet",
    date: "9/21 09:30",
    basis: "商談日時・希望条件が一致",
    summary: "初期費用を抑えて、手元資金を残す購入プランを相談。",
    linked: false,
  },
];
export const initialPolicies = [
  {
    id: "pol1",
    title: "予約・日程希望への返信",
    desc: "明確な日時希望に対し、空き枠をご案内。",
    level: 2,
    rate: 98,
    edits: 0,
  },
  {
    id: "pol2",
    title: "コンテンツ閲覧後のフォロー",
    desc: "閲覧内容と顧客の相談履歴に合わせたご連絡。",
    level: 1,
    rate: 91,
    edits: 0,
  },
  {
    id: "pol3",
    title: "商談後の検討サポート",
    desc: "面談で伺った懸念に、事例や資料でお応え。",
    level: 1,
    rate: 84,
    edits: 5,
  },
  {
    id: "pol4",
    title: "外部ニュースのご案内",
    desc: "市況や制度改定の情報から、候補を抽出。",
    level: 0,
    rate: 70,
    edits: 12,
  },
];
export const integrations = [
  {
    id: "line",
    name: "LINE Harness",
    letter: "L",
    tone: "sage",
    desc: "公式LINEのメッセージ・シナリオ",
    sync: "09:18",
  },
  {
    id: "sheets",
    name: "Google Sheets",
    letter: "S",
    tone: "sage",
    desc: "物件・商品マスタの取り込み",
    sync: "09:15",
  },
  {
    id: "drive",
    name: "Google Drive",
    letter: "D",
    tone: "peach",
    desc: "面談録音と議事録の取り込み",
    sync: "09:12",
  },
  {
    id: "calendar",
    name: "Google Calendar",
    letter: "31",
    tone: "blue",
    desc: "担当者の空き枠・面談予定",
    sync: "09:18",
  },
  {
    id: "timerex",
    name: "TimeRex",
    letter: "T",
    tone: "lavender",
    desc: "日程調整・予約の確定",
    sync: "09:16",
  },
];
export const auditRows = [
  [
    "田中 翔太",
    "佐藤 健一",
    "2026/09/19 14:00",
    "資金計画動画を閲覧後の個別提案",
    "課金確定",
    30000,
  ],
  [
    "山本 美咲",
    "佐藤 健一",
    "2026/09/20 11:00",
    "初期費用の事例からの再予約",
    "課金確定",
    30000,
  ],
  [
    "斉藤 隆",
    "田中 雅人",
    "2026/09/21 16:00",
    "新着物件のご案内",
    "確認中",
    30000,
  ],
  [
    "伊藤 恵子",
    "佐藤 健一",
    "2026/09/22 13:00",
    "再連絡への返信から予約",
    "実施待ち",
    0,
  ],
];
export const periods = {
  7: { label: "9/15 – 9/21", values: [1, 2, 1, 2, 1, 3, 2] },
  14: {
    label: "9/8 – 9/21",
    values: [2, 1, 3, 2, 1, 3, 2, 1, 2, 1, 2, 1, 3, 2],
  },
  30: {
    label: "8/23 – 9/21",
    values: [
      1, 0, 1, 2, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 3, 2, 1, 3, 2, 1, 2,
      1, 2, 1, 3, 2,
    ],
  },
};
